DockerfileLambda
src/PwrDrvr.LambdaDispatch.LambdaLB/PwrDrvr.LambdaDispatch.LambdaLB.csproj

Issue 63 - Statically link openssl

---

.vscode/launch.json
ecr.template.yaml
fargate.template.yaml
src/PwrDrvr.LambdaDispatch.Router/Config.cs
src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstanceManager.cs
src/PwrDrvr.LambdaDispatch.Router/PwrDrvr.LambdaDispatch.Router.csproj
src/PwrDrvr.LambdaDispatch.Router/Startup.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/ConfigTests.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/LambdaInstanceTests.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/LeastOutstandingQueueTests.cs

Issue-17 - Configuration of FunctionName and MaxConcurrentCount

---

.vscode/tasks.json
src/PwrDrvr.LambdaDispatch.Extension/HttpReverseRequester.cs
src/PwrDrvr.LambdaDispatch.Extension/PwrDrvr.LambdaDispatch.Extension.csproj
src/PwrDrvr.LambdaDispatch.Extension/SetupHttpClient.cs
src/PwrDrvr.LambdaDispatch.Router/Config.cs
src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstanceManager.cs
src/PwrDrvr.LambdaDispatch.Router/Program.cs
src/PwrDrvr.LambdaDispatch.Router/PwrDrvr.LambdaDispatch.Router.csproj
src/demo-app/app.cjs

- Allow registering runners that are not created by the extension for testing purposes

Issue-69 - Add debug feature for testing Rust

---

DockerfileExtension
DockerfileLambdaDemoApp
src/PwrDrvr.LambdaDispatch.Extension/Function.cs
src/demo-app/startapp.sh

Issue 72 - Use Extension to Start lambda-dispatch

---

fargate.template.yaml
src/PwrDrvr.LambdaDispatch.Extension/Function.cs
src/PwrDrvr.LambdaDispatch.Extension/SetupHttpClient.cs
src/PwrDrvr.LambdaDispatch.Router/Config.cs
src/PwrDrvr.LambdaDispatch.Router/Program.cs
src/demo-app/app.cjs

Issue 75 - Runtime config of insecure http2 control channels

---

src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/LeastOutstandingQueue.cs

Issue 71 - Improve background dispatching

---

src/PwrDrvr.LambdaDispatch.Extension/HttpReverseRequester.cs
src/PwrDrvr.LambdaDispatch.Router/Areas/ControlChannels/Controllers/ChunkedController.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs

Abort the request to the Lambda if the incoming request to the router aborts.
Fixes #81

Issue 81 - Handle incoming request abort

---

src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs

This issue was primarily observed with the Rust extension as the replacement request would arrive around the same time as the new `oha` request 2x-4x more often than with the DotNet extension and this caused background dispatches which would sleep 10 ms between each attempt to dispatch.
Added a short spin loop to try dispatching in this case.

Issue 20 - Fix degenerate case for dispatching with 1 channel from 1 extension

---

extension/src/run.rs
src/demo-app/app.cjs

Issue 93 - Fix panic on odd status codes

---

src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs

Issue 99 - Handle exceptions on extension response headers

---

src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs

Issue 104 - Handle response header key repeats

---

src/demo-app/app.cjs
src/demo-app/package-lock.json
src/demo-app/package.json

Issue 111 - Demo App Multiple Workers

---

fargate.template.yaml

- Allows scaling up
- Allows scaling down
- Tested and observed to work
Fixes #112

Issue 112 - CloudFormation Only - ECS Auto Scaling

---

extension/src/app_request.rs
extension/src/app_start.rs
extension/src/lambda_request.rs
extension/src/options.rs
extension/src/ping.rs
extension/src/router_channel.rs

Removes allocations that could be removed without otherwise changing the structure of the code (as well as some minor tidyings).

Fix low hangin fruit extra allocs

---

src/PwrDrvr.LambdaDispatch.Router/MetadataService.cs
src/PwrDrvr.LambdaDispatch.Router/Program.cs
src/PwrDrvr.LambdaDispatch.Router/PwrDrvr.LambdaDispatch.Router.csproj

Issue 151 - Add AWSSDK.SecurityToken

---

.github/workflows/build.yaml

Issue 156 - Add docker tags

---

src/PwrDrvr.LambdaDispatch.Router/Config.cs
src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/PendingRequest.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/DispatcherSimpleTests.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/DispatcherTests.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/PendingRequestTests.cs

- Fixes #165
- Fix decrementing `PendingCount` on non-dispatched request (was never being decremented)
- Fix race condition on state change to Aborted or Dispatched for PendingRequest

Issue 165 - Fix pending never dispatched

---

extension/src/lambda_request.rs
extension/src/prelude.rs
extension/src/router_channel.rs

Issue 147 - Do not clone the RNG

---

src/PwrDrvr.LambdaDispatch.Router/Areas/ControlChannels/Controllers/ChunkedController.cs
src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs
src/PwrDrvr.LambdaDispatch.Router/PoolManager.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/PoolManagerTests.cs

Issue 154 - Tight Loop - Race Condition Fix in PoolManager

---

src/PwrDrvr.LambdaDispatch.Router/Program.cs
src/PwrDrvr.LambdaDispatch.Router/PwrDrvr.LambdaDispatch.Router.csproj

- Fixes #149 broken pipe when running echo of 160 MB POST

Issue 149 - Remove the body size limits

---

.github/actions/coverage-report/action.yml
.github/workflows/build.yaml
scripts/parse-coverage.js

Fixes #163 for both DotNet and Rust

Issue-163 - Comment with code coverage summary

---

extension/src/app_request.rs
extension/src/endpoint.rs
extension/src/lambda_request.rs
extension/src/lambda_service.rs
extension/src/router_channel.rs

Use a connection pooling client for contained app connections

---

extension/src/lambda_service.rs
extension/src/test_mock_router.rs

Issue-181 - Add header size tests

---

extension/src/app_request.rs
extension/src/lambda_request.rs
extension/src/router_channel.rs
extension/src/test_mock_router.rs

Issue-199 - Fix `//` path handling in extension - Issue introduced in 0.9.7

---

Cargo.lock
DEVELOPMENT.md
extension/Cargo.toml

- Document how to setup rust dev env
- Document how to setup dotnet dev env
- Test on a non-setup machine

Update dev docs

---

extension/tests/app_request.rs
extension/tests/lambda_service.rs
extension/tests/router_channel.rs
extension/tests/support/mock_router.rs

- Build the params for the mock router using a builder

Issue-185 - Mock Router Builder

---

src/PwrDrvr.LambdaDispatch.Router/Program.cs

- Log if cert file is missing
- Do not try to open HTTPS ports if there is no cert file
- Do not throw exception / crash if no cert file

Issue 2 - Handle missing cert file

---

extension/src/lambda_request.rs

- Log the endpoint (url) when lambda cannot connect to ECS

Issue 2 - Log Endpoint on Connect Failure

---

Cargo.lock
extension/Cargo.toml

- Fixes build, if I recall correctly

Issue 218 - Cargo update

---

.github/actions/configure-nodejs/action.yml
.github/workflows/pr.yaml

Issue-225 - Node Module Cache

---

.github/workflows/build.yaml
src/cdk-construct/API.md
src/cdk-construct/src/ecs.ts
src/cdk-construct/src/lambda.ts
src/cdk-stack/src/lambda-dispatch-stack.ts
src/cdk-stack/src/main.ts

Issue-230 - Fargate spot

---

.github/workflows/build.yaml
src/cdk-stack/src/ecr-stack.ts
src/cdk-stack/src/ecs-cluster-stack.ts
src/cdk-stack/src/main.ts
src/cdk-stack/src/vpc-stack.ts
src/cdk-stack/test/__snapshots__/main.test.ts.snap

Issue-227 - Prep for CDK publish

---

.github/workflows/build.yaml
src/cdk-construct/.projen/tasks.json
src/cdk-construct/.projenrc.ts
src/cdk-construct/DockerfileLambda
src/cdk-construct/src/lambda.ts
src/cdk-construct/test/hello.test.ts
src/cdk-construct/test/lambda.test.ts
src/cdk-stack/src/lambda-dispatch-stack.ts
src/cdk-stack/src/main.ts
src/cdk-stack/test/__snapshots__/main.test.ts.snap

Issue-238 - Try to get public images working

---

src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/DispatcherTests.cs

Issue 214 - Fix negative pending requests

---

package.json
src/cdk-construct/.projenrc.ts
src/cdk-construct/API.md
src/cdk-construct/package.json
src/cdk-stack/.projen/deps.json
src/cdk-stack/.projen/tasks.json
src/cdk-stack/.projenrc.ts
src/cdk-stack/package.json
src/cdk-stack/src/lambda-dispatch-stack.ts
src/cdk-stack/test/__snapshots__/main.test.ts.snap

Issue-227 - Rename CDK packages

---

.github/workflows/build.yaml
src/cdk-stack/src/main.ts

Issue-258 - Add SHA tag for each build of demo-app

---

.github/workflows/build.yaml
src/cdk-stack/src/lambda-dispatch-stack.ts

Issue-260 - Add sha suffix to PR router image tag

---

src/PwrDrvr.LambdaDispatch.Router/LoggerInstance.cs

Issue-262 - Use AWS logger for ECS

---

src/PwrDrvr.LambdaDispatch.Router/Areas/ControlChannels/Controllers/ChunkedController.cs
src/PwrDrvr.LambdaDispatch.Router/Config.cs
src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstanceManager.cs
src/PwrDrvr.LambdaDispatch.Router/PwrDrvr.LambdaDispatch.Router.csproj
src/PwrDrvr.LambdaDispatch.Router/Startup.cs

Issue-253 - Option to disable MetricsRegistry usage

---

DEVELOPMENT-CURRENT-COMMANDS.md
src/cdk-construct/src/ecs.ts

Issue-250 - Drop min worker threads to 1 on router

---

src/PwrDrvr.LambdaDispatch.Router/Config.cs
src/PwrDrvr.LambdaDispatch.Router/Program.cs
src/PwrDrvr.LambdaDispatch.Router/Startup.cs

Issue-253 - Config option to disable the periodic metrics
