pwrdrvr/lambda-dispatch

src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/Program.cs

- Shorten the number of quick loops - we are just checking for a race condition
- Exit the quick loop as soon as there are no pending requests
- Make the channel bounded - this may happen to a few requests but it is an extreme edge case and we're just trying to prime the pump to get things going

Issue 71 - A few final cleanups for background dispatch

---

src/PwrDrvr.LambdaDispatch.Router/Config.cs
src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstanceManager.cs
src/PwrDrvr.LambdaDispatch.Router/LeastOutstandingQueue.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/LambdaInstanceTests.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/LeastOutstandingQueueTests.cs

- Add Least Outstanding Queue test
- Count the number of connections for a lambda independently of the number of outstanding requests for it
- A low number of outstanding requests makes an instance is relatively idle even if it has only 1 remaining open connection (e.g. if it has not yet re-established connections that were just used)
- Instances with low counts of outstanding requests should be dispatched to first, but once the last open connection is used (even if not the max) then they should be moved to the full instance list

Issue 5 - Connections independent of requests

---

src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs

- Rust extension can handle duplex request/response (`/echo`) but dotnet extension can only handle simplex request/response still (`/echo-slow`)
- Relaying the `oha` binary (`9771960` bytes) locally on an M2 Max goes from 74 RPS before to 76-78 RPS after
- This should also enable long-lived request/responses used as a socket as in this application
Fixes #20 
```log
oha -c 10 -z 10s -m POST -T application/octet-stream -D ./oha http://localhost:5001/echo
Summary:
Success rate: 100.00%
Total:        10.0010 secs
Slowest:      0.4269 secs
Fastest:      0.1223 secs
Average:      0.1307 secs
Requests/sec: 75.9927
Total data:   6.92 GiB
Size/request: 9.32 MiB
Size/sec:     708.20 MiB
Response time histogram:
0.122 [1]   |
0.153 [749] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.183 [0]   |
0.214 [0]   | …
```

Issue 20 - Duplex router request response

---

Cargo.lock
ChannelError.md
DEVELOPMENT.md
extension/Cargo.toml
extension/src/app_request.rs
extension/src/app_start.rs
extension/src/counter_drop.rs
extension/src/main.rs
extension/src/ping.rs
extension/src/run.rs
fargate.template.yaml
src/PwrDrvr.LambdaDispatch.Extension/HttpReverseRequester.cs
src/PwrDrvr.LambdaDispatch.Router/Areas/ControlChannels/Controllers/ChunkedController.cs
src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstanceManager.cs

- Converted extension to a logging framework from `println`
- Fixed uninitialized memory read in the Router when parsing HTTP
- Fixed error when first char was `\n` of HTTP response
- Added logging statements and in-flight-request counting
- All in an attempt to debug the hang on `/echo` that only happens when deployed to Lambda (obviously a race condition of some sort)

Issue 86 - Logging / debug `/echo` hang

---

extension/src/app_request.rs
extension/src/run.rs
src/demo-app/app.cjs

- Only pass the path on the request to the contained app
- Add a `/headers` method to the demo-app to reply with the headers
- Mark the POST to the router as `application/octet-stream` not as `application/json`

Issue 91 - Fix URL Path

---

src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs
src/demo-app/app.cjs

- Add the query string
- Make sure to use the encoded query and path
Fixes #101

Issue 101 - Pass through query string

---

extension/src/main.rs
extension/src/messages.rs
src/PwrDrvr.LambdaDispatch.Extension/Function.cs
src/PwrDrvr.LambdaDispatch.Messages/Waiter.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstanceManager.cs
src/PwrDrvr.LambdaDispatch.Router/MetricsRegistry.cs

- Invoke a "buddy" lambda each time we start a lambda
- The buddy lambda only performs the init then returns
- This is a way to nearly-guarantee that we will have an exec env ready when an exec env ends normally before it's timeout is reached
- Start the replacement lambda as soon as a lambda asks for a close
- This prevents a drop in capacity during instance replacement
- This can be rather pronounced when running only a few instances
- Remove stopping instances from the count of which instances satisfy the desired instance count 
- Use locks around instance state changes - these are rare but allowing double transitions will throw off the counts of running instances
Fixes #89

Issue 89 - Add init-only lambda invokes

---

src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs
src/PwrDrvr.LambdaDispatch.Router/Program.cs

- The router was passing the incoming protocol version to the extension, which was wrong
- The router was not listening on the HTTPS/HTTP2 port at all

Issue 67 - Enable https/http2 to the router

---

fargate.template.yaml
src/PwrDrvr.LambdaDispatch.Router/Program.cs

- Deployed on ECS
- 1 CPU: 4000 RPS -> 4500-5000 RPS with `-c 100` on `/ping`
- Same response time and RPS rate as directlambda
- Locally
- Cuts CPU from 380% to 120%
- `-c 10` on `/ping`
Click to view on YouTube
[![DotNot as efficient as Rust?](https://img.youtube.com/vi/jE5_EVSSVvc/maxresdefault.jpg)](https://www.youtube.com/watch?v=jE5_EVSSVvc)
Fixes #109

Issue 109 - Limit to 1 worker thread in Router

---

DockerfileLambdaDemoApp
README.md
extension/src/main.rs
fargate.template.yaml

Issue 108 - Specify LAMBDA_DISPATCH_RUNTIME

---

src/PwrDrvr.LambdaDispatch.Router/EmbeddedMetrics/MetricsLogger.cs
src/PwrDrvr.LambdaDispatch.Router/EmbeddedMetrics/Unit.cs
src/PwrDrvr.LambdaDispatch.Router/GetCallbackIP.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstance.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstanceManager.cs
src/PwrDrvr.LambdaDispatch.Router/MetadataService.cs
src/PwrDrvr.LambdaDispatch.Router/Program.cs
src/PwrDrvr.LambdaDispatch.Router/PwrDrvr.LambdaDispatch.Router.csproj
test/PwrDrvr.LambdaDispatch.Router.Tests/ConfigTests.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/LambdaInstanceTests.cs
test/PwrDrvr.LambdaDispatch.Router.Tests/MetadataServiceTests.cs

- AWS `MetadataService` class
- Extend the AWS metadata fetching to support both ECS and EC2 (in theory, not tested yet)
- Use sync HTTP calls for the AWS metadata calls for ECS (not supported by the AWS SDK directly) since the AWS SDK also makes sync HTTP calls as the metadata endpoint is designed to be very fast
- Remove layers of async/await that were only needed because the callback IP was loaded async
- Add support for getting the ECS cluster name, used in the `MetricsLogger` below
- AWS CloudWatch EmbeddedMetricsFormat (EMF) `MetricsLogger` class
- Add a class that can emit metrics about the timing of every single request
- Set dimensions for the metrics to include the cluster name
- Add some initial metrics

Issue 124 - AWS Metadata Service & Embedded Metrics Logger

---

config.json
src/PwrDrvr.LambdaDispatch.Router/LambdaClientConfig.cs

- This no longer needs to be 8
- Set it to 1 to ensure that we do not "stack up" invokes

Issue 124 - Drop Lambda Invoke retries

---

Cargo.lock
extension/Cargo.toml
extension/src/main.rs
extension/src/messages.rs
extension/src/run.rs

- Attempted to make no logic changes
- Split `run` into several functions
- Created 3 classes:
- `LambdaService`
- Implements the interface/trait needed for `lambda_runtime::run`
- `LambdaRequest`
- Handles context around a single request for a given `lambda_id`
- `RouterChannel`
- Handles the request loop for a single channel back to the router

Extension - Refactor to implement Tower.Service

---

extension/src/app_request.rs
extension/src/app_start.rs
extension/src/endpoint.rs
extension/src/lambda_request.rs
extension/src/lambda_service.rs
extension/src/main.rs
extension/src/messages.rs
extension/src/options.rs
extension/src/ping.rs
extension/src/prelude.rs
extension/src/router_channel.rs

This PR contains a variety of changes I made while building my understanding of the code. I some attempt to keep commits focused on a particular change. While reviewing the code, it will probably be helpful to look at each individual commit.
- `f9673cf` fully adopt anyhow errors - Standardizes on `anyhow::{Error, Result}` instead of mixing `std::io::Result` and `dyn Error`. Also makes use of `Context` trait for relaying error messages as results.
- `6340a90` use less boiler plate polling ready - The `ready` function is much less code and does the exact same thing under the hood.
- `2efc781` cleanup unused imports
- `7b5b40c` construct close/ping urls outside of loop - These urls do not change once computed, allocating them before the loop reduces unnecessary allocations.
- `1b606df` make …

Various refactorings, improvements. 

---

.dockerignore
.github/actions/setup-gcc-musl-cross/action.yml
.github/workflows/build.yaml
DockerfileExtensionCross

- Build `aarch64` extension on x64 using cross-compiler
- Build outside of Docker as it's quite a bit faster
- Cache the cargo sources
- Cache the cross-compiler
- Upgrade the version of Rust
- Simplify the Dockerfile (just copies in the single built binary file)

Issue-188 - Use setup-rust

---

DEVELOPMENT-CURRENT-COMMANDS.md
extension/src/app_request.rs
extension/src/app_start.rs
extension/src/connect_to_app.rs
extension/src/lambda_request.rs
extension/src/lambda_request_error.rs
extension/src/lambda_service.rs
extension/src/main.rs
extension/src/messages.rs
extension/src/ping.rs
extension/src/router_channel.rs
extension/src/test_mock_router.rs

- ENHANCEMENT: Move contained app response relay to a task and await both the request and response relay tasks
- FIX: Tell other channels to stop looping when 1 channel stops looping
- ENHANCEMENT: Propagate detailed errors and exit reasons all the way back to the router
- FIX/ENHANCEMENT: Remove hiding of errors (non-consumed results)
- ENHANCEMENT: Handle Channel 5xx, 4xx, and Other ExitReasons
Fixes #182

Issue 182 - Error handling, propagation, etc.

---

extension/src/app_request.rs
extension/src/router_channel.rs
extension/src/test_mock_router.rs

- Fix error in mock router `Get` request type that did not wait to finish the headers

Issue-199 - Use mock_router in app_request tests

---

.github/workflows/build.yaml

Issue 264 - Use updated extension for demo app on PRs

---

src/cdk-construct/.github/workflows/build.yml
src/cdk-construct/.github/workflows/release.yml
src/cdk-construct/.mergify.yml
src/cdk-construct/.projen/tasks.json
src/cdk-construct/.projenrc.ts
src/cdk-construct/package.json

Issue-251 - Enable other langs for CDK

---

.github/workflows/build.yaml

- Fixes incompatibility with artifacts v4
- Updates artifacts from v3 to v4

Update artifacts version

---

package.json
src/demo-app/app.cjs
src/demo-app/package.json

Disable demo-app logs by default

---

src/PwrDrvr.LambdaDispatch.Extension/Function.cs
src/PwrDrvr.LambdaDispatch.Extension/HttpDuplexContent.cs
src/PwrDrvr.LambdaDispatch.Extension/HttpReverseRequester.cs
src/PwrDrvr.LambdaDispatch.Router/Dispatcher.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaConnection.cs
src/PwrDrvr.LambdaDispatch.Router/LambdaInstanceManager.cs
src/PwrDrvr.LambdaDispatch.Router/LeastOutstandingQueue.cs
src/PwrDrvr.LambdaDispatch.Router/MetricsRegistry.cs
src/PwrDrvr.LambdaDispatch.Router/Startup.cs
test/PwrDrvr.LambdaDispatch.Router.TestClient/Program.cs

- Turns out this is actually only needed in library code

Issue-223 - Remove ConfigureAwait

---

.github/workflows/build.yml

https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f#:~:text=Contrary%20to%20if%3A%20always%28%29%2C%20if%3A%20success%28%29%20%7C%7C%20failure%28%29,run%3A%20%7C%20echo%20Hello%20Read%20more%20in%20here.

Fix deploy cancel
